output "fabric_connection_id" {
  value = module.equinix-fabric-connection-oci.fabric_connection_uuid
}

output "fabric_connection_name" {
  value = module.equinix-fabric-connection-oci.fabric_connection_name
}

output "fabric_connection_status" {
  value = module.equinix-fabric-connection-oci.fabric_connection_status
}

output "fabric_connection_provider_status" {
  value = module.equinix-fabric-connection-oci.fabric_connection_provider_status
}

output "network_edge_bgp_state" {
  description = "Network Edge device BGP peer state."
  value       = module.equinix-fabric-connection-oci.network_edge_bgp_state
}

output "network_edge_bgp_provisioning_status" {
  description = "Network Edge device BGP peering configuration provisioning status."
  value       = module.equinix-fabric-connection-oci.network_edge_bgp_provisioning_status
}

output "oci_drg_name" {
  description = "Dynamic Routing Gateway (DRG) name."
  value       = module.equinix-fabric-connection-oci.oci_drg_name
}

output "oci_drg_id" {
  description = "Dynamic Routing Gateway (DRG) id."
  value       = module.equinix-fabric-connection-oci.oci_drg_id
}

output "oci_drg_autogenerated_vcn_route_table_id" {
  description = "Dynamic Routing Gateway (DRG) default route table for VCN."
  value       = module.equinix-fabric-connection-oci.oci_drg_autogenerated_vcn_route_table_id
}

output "oci_drg_autogenerated_generic_route_table_id" {
  description = "Dynamic Routing Gateway (DRG) default route table for all but VCN attachments: RPC, IPSec, VC."
  value       = module.equinix-fabric-connection-oci.oci_drg_autogenerated_generic_route_table_id
}
